# Generated by Django 2.2 on 2019-04-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='email_id',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(max_length=20),
        ),
    ]
