# Generated by Django 2.2 on 2019-04-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190404_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='User_detail',
        ),
    ]
