# Generated by Django 2.2 on 2019-04-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190404_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='number',
            field=models.IntegerField(),
        ),
    ]
